language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

notifications:
  email:
    on_failure: change # [always|never|change] default: always
    
# no dependencies (coveralls, ipython only needed for testing)
install: pip install coveralls ipython

script: nosetests --with-doctest --with-coverage --cover-package=param

after_success: coveralls
